version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: ril
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: ril
    ports:
      - 3306:3306
    volumes:
      - ./.sql:/docker-entrypoint-initdb.d
